name: formatter

on: push

env:
  FILE_PATTERN: "src/**/*.{ts,tsx,js,jsx,css,scss}"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
        with:
          node-version: 16
    - name: format
      run: |
        npm install -g prettier
        npx prettier --write ${FILE_PATTERN}
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        commit_message: format by Github Actions
